const Handlers = {
    GetAddressesRoomFollowCount: "get-addresses-room-follow-count",
    GetChatFollows: "get-chat-follows",
    GetChatPosts: "get-chat-posts",
    GetChatRoomFollowCount: "get-chat-room-follow-count",
    GetChatRoomFollows: "get-chat-room-follows",
    GetProfileInfo: "get-profile-info",
    GetProfileLinks: "get-profile-links",
    GetRecentRoomFollow: "get-recent-room-follow",
    GetRecentSetName: "get-recent-set-name",
    GetRecentSetProfile: "get-recent-set-profile",
    GetRecentSetPic: "get-recent-set-pic",
    GetRecentFollow: "get-recent-follow",
    GetFollowers: "get-followers",
    GetFollowing: "get-following",
    GetLikes: "get-likes",
    GetLinkedAddresses: "get-linked-addresses",
    GetWalletLinks: "get-wallet-links",
    GetAddressAliases: "get-address-aliases",
    GetNewPosts: "get-new-posts",
    GetNotifications: "get-notifications",
    GetPost: "get-post",
    GetPosts: "get-posts",
    GetPostParent: "get-post-parent",
    GetPostReplies: "get-post-replies",
    SetWindowStorage: "set-window-storage",
    GetWindowStorage: "get-window-storage",
    RightClickMenu: "right-click-menu",
    CoinsMenu: "coins-menu",
    BrowserWindowFocus: "browser-window-focus",
    OpenExternal: "open-external",
    OpenFileDialog: "open-file-dialog",
    ShowMessageDialog: "show-message-dialog",
    ShowNotification: "show-notification",
    GetWindowId: "get-window-id",
    GetAppInfo: "get-app-info",
    CloseWindow: "close-window",
    ClearClipboard: "clear-clipboard",
    CheckWalletFile: "check-wallet-file",
    AuthenticateWallet: "authenticate-wallet",
    ConfirmSeed: "confirm-seed",
    CreateWallet: "create-wallet",
    GenerateSeed: "generate-seed",
    ImportSeed: "import-seed",
    ExportPrivateKey: "export-private-key",
    ExportSeed: "export-seed",
    RemovePrivateKey: "remove-private-key",
    GetExistingWalletFiles: "get-existing-wallet-files",
    GetNetworkConfig: "get-network-config",
    GetWallet: "get-wallet",
    GetWalletFileInfo: "get-wallet-file-info",
    SaveNetworkConfig: "save-network-config",
    SignTransaction: "sign-transaction",
    SignOnParentSession: "sign-on-parent-session",
    SignOnSessionResult: "sign-on-session-result",
    SpendPromptReply: "spend-prompt-reply",
    UnlockWallet: "unlock-wallet",
    UpdateWallet: "update-wallet",
    WalletLoaded: "wallet-loaded",
    GetWalletInfo: "get-wallet-info",
    GraphQL: "graphql",
    // The syncs main runs against the index on the renderer's behalf. The
    // renderer names what to sync and hears progress on a per-request
    // listener; every write to the database happens on this side.
    SyncHistory: "sync-history",
    SyncSlp: "sync-slp",
    SyncBlock: "sync-block",
    SyncAliases: "sync-aliases",
    SyncProfiles: "sync-profiles",
    SyncProfileLinks: "sync-profile-links",
    SyncLinkedProfiles: "sync-linked-profiles",
    SyncPosts: "sync-posts",
    SyncNewPosts: "sync-new-posts",
    SyncChat: "sync-chat",
    SyncChatFollows: "sync-chat-follows",
    FetchTransaction: "fetch-transaction",
    SyncListen: "sync-listen",
    SyncListenClose: "sync-listen-close",
    GetWindowNetwork: "get-window-network",
    // A window's network is chosen by id from the configuration main holds;
    // the page never hands main a server of its own.
    SelectNetwork: "select-network",
    GetTheme: "get-theme",
    SetTheme: "set-theme",
    CheckForUpdates: "check-for-updates",
    GetUpdatePrefs: "get-update-prefs",
    SetUpdatePrefs: "set-update-prefs",
    OpenPreviewSend: "open-preview-send",
    OpenTransaction: "open-transaction",
    GetPic: "get-pic",
    GetTransactions: "get-transactions",
    GetUtxos: "get-utxos",
    GetTransaction: "get-transaction",
    GetCoins: "get-coins",
    GetAddressTokenBalances: "get-address-token-balances",
    GetTokenBalances: "get-token-balances",
    GetTokenBatons: "get-token-batons",
    GetSlpGenesis: "get-slp-genesis",
}

const Listeners = {
    DisplayModal: "display-modal",
    SignOnSession: "sign-on-session",
    SpendPromptStep: "spend-prompt-step",
    SelectTab: "select-tab",
    ToggleTab: "toggle-tab",
    SyncClosePrefix: "sync-close-",
    SyncDataPrefix: "sync-data-",
    SyncOpenPrefix: "sync-open-",
    SyncProgressPrefix: "sync-progress-",
}

module.exports = {
    Handlers: Handlers,
    Listeners: Listeners,
}
