const Modals = {
    None: "none",
    Address: "address",
    Remove: "remove",
    Settings: "settings",
    ChatRoomFollowers: "chat-room-followers",
    ChatRoomFollowing: "chat-room-following",
    ChatRoomLoad: "chat-room-load",
    ChatRoomJoin: "chat-room-join",
    Followers: "followers",
    Following: "following",
    Key: "key",
    Links: "links",
    NetworkView: "network-view",
    Password: "password",
    Post: "post",
    PostCreate: "post-create",
    PostLike: "post-like",
    PostLikes: "post-likes",
    PostReply: "post-reply",
    ProfileFind: "profile-find",
    ProfileSetName: "profile-set-name",
    ProfileSetPic: "profile-set-pic",
    ProfileSetText: "profile-set-text",
    ProfileView: "profile-view",
    Seed: "seed",
    TokenCreate: "token-create",
    TokenMint: "token-mint",
    TokenSend: "token-send",
}

module.exports = {
    Modals: Modals,
}
